// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngiwmpojxorgdozstwiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5naXdtcG9qeG9yZ2RvenN0d2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTEyMDAsImV4cCI6MjA3Mzg2NzIwMH0.inJwcNBLRK8Sb29P0mPeDF1zSxAMsuymKKnLsMFmQ1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});